[firebase]
type = "service_account"
project_id = "dopamine-coffee"
private_key_id = "e2e470074b85a908502269c563f649e701da21b2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC649q4b6jFxnlp
1QVJnmVVYJCKtJG92sI28zzEFVIF23u+za4ptVf81B65UB/hp4IeC5EFnOIWTXI5
KCcv3plk2vrtOJhNB6451KFrLBOEqHv0iemj+sFU3R3RvjVKgD6ljUh8i3GUYGKj
QU6gdqCVUTfS0+pNAgPmlavByBPD+6vzWY4z9XQHq4oi+vkS58nkEr3/n3d/zWJN
XU2y8YhgTNA2J0XpIJUV9MFGX2qqsFBG4UOfsHg7z2ZKiZiT39uyBZwGaUb6oETO
oRYBdDauA352PqT9hU2kTIACQHiVGp6tOfXRD06JNMyJ0SYupx8d9r0vead8FWCo
meuXAif7AgMBAAECggEAHJy8xCboJltUBEVmOVakOfV+O5YYiAIBYOtNXtHKzHXF
VLlllCIc1erdx05Ci0gbbiEkM0FJBdQWjDSfBz+jqWKzLvVOr+Bgpp7slZ1aYaFv
1Mj2ebHuvmDZ614dB4ppzOu78MFigq5c+5SIhp2SyTl1e/QQt3h7A2bftFu+1u6h
+A0S5EitNNbx3icBDuex7PyjYOFXRNQzbGBObxDoG1SXaz4hxc0n5kr32bYZXTxa
60Yfef1G5c7AWR8S5ofqcGFS8aF84JvD+Ah8AolVt0226Go5ljG2YkCvssqr+qba
kXt2k+etOKnS73Zs0bXUXAqox/ag+MqsvC2hDs3DMQKBgQD2mWvOxaUJnH2cOoaE
QBLUmmkUtgn7fb/2QiJQavw2hodauFHVhhlqASYizDuUTmNaV863H8LECCrWwi3C
LWfCKNl3De3zBvurNpm168J+VwCCHvlGCatheQF8oVf64EhhK46/KX/fsTowHTVZ
i1/smgnYbLhup7ffNjf+QHZv0QKBgQDCA7oOitZuVbE8CzV+bp36igI9B2GB7E1U
Wgazw6TeNnkqBhfAOTYl7bwn173G/gTTwP39kIGqYGD0ufyKSar9PtRDnV8BsMDE
Gy/7CK+OwqwG3MJ0sWdfgifKqQqB/Alb2PQEhZgNvU1nNNZfn6Awsb+8xsAGQwSc
w4w2HrY6CwKBgEvsvMazD7c/2WTKmDQLzkBrMkNQMQ6fjwTxI8OCzRi0nuQNsBR/
7z82D1nTa9yjre9Y7apwOvVEVnw82P3aIQIktZ/0R/j1g3MZooXiisV/YAawJqur
unqOWSjYPFBf0akpUhAFZPuog3Pg6lYhlW0xmCpsfvSC6xfsh5zemBihAoGBAJUH
UdK72OzVzBdoMMYWaCk7+24vjjnDbr79jCpnfOvoAfhCx9my2KIX1DDyqmcBVmnl
0/QDHWbnM3KorpD2924h5eCuMH1W7St2CswUpu3NIWEAECqc3t/hVXl5kYW5OOMh
aodSqzLal2tQjd7T+bONxc9XB8eHkTJtjvU/cBBzAoGBAKPHK9vc59hOq3YIjSqE
v74JhzRQG8TxyfMqNJLAEA6OlHh4zLGmTRgbxotFhtaczWrZ1cATnNoTr3wR6EW9
f/AW0y8B8oTZXhkWcYdlzApxpYf79A0fUQzZFzvEi+xdNiVe1gIMqTpQzv/jEc9Q
AKZK75cgpPsLXZJv+G68xLOL
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@dopamine-coffee.iam.gserviceaccount.com"
client_id = "103365074990004978746"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@dopamine-coffee.iam.gserviceaccount.com"
